tags/prototype-20100226/grails-app/controllers/DiscoveryController.groovy
import resolver.DatabaseContentResolver
import resolver.Resolveable
import resolver.OscarResolver
import resolver.SingleLineRegExpressionResolver
import types.Hit
import com.fiehn.util.StopListParser

/**
 * this controller is used to discover chemical compounds in the given parameter
 */
class DiscoveryController {

  DiscoveryService discoveryService

  def index = { }
  /**
   * process a query and returns a map containning all the found chemical names
   */
  def process = {

    //logger is added automatically by grails
    log.debug "executing a query..."

    //params are added automatically by grails
    assert (params.query != null)

    def limitConfidence = 0.5

    //if we don't have a confidence limit set we use the default
    //otherwise we assign on
    if (params.limitConfidence != null) {
      limitConfidence = params.limitConfidence
    }

    log.debug "params.query ::: "+params.query
 
    //contains the final result
    Collection<Map<Compound, ?>> result = discoveryService.process(params.query ,limitConfidence)

    //forward to the controller
    return [result: result]
  }

  
}

tags/prototype-20100226/grails-app/views/discovery/index.gsp
<%--
  Created by IntelliJ IDEA.
  User: wohlgemuth
  Date: Feb 2, 2010
  Time: 2:40:38 PM
  To change this template use File | Settings | File Templates.
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head><title>Discovery</title>
</head>
<style type="text/css">@import url("${createLinkTo(dir: 'css',file : 'WebGUIStandards.css')}");</style>

<body topMargin=0 background="${createLinkTo(dir: 'images',file : 'FormBG.gif')}"  >

<div id="contents">

    <div id="main">
<g:form name="discoveryForm" controller="discovery">

  <table id='tabTitle' border='0' width="60%" align='center' cellpadding="0" cellspacing="0">
      <tr>
          <td colspan="6" class="AppsLabel" align="center"> Discovery </td>
      </tr>
      <tr>
          <td colspan="6" class="TableHeaderDescription" align="center"> here you can discover compound in your provided text</td>
      </tr>
      <tr>
          <td colspan="6" align='right'>
                    [ <g:link controller="homePage" action="index">Back to home</g:link> ]
          </td>
      </tr>

    <tr height='2'> <td> &nbsp; </td> </tr>

    <tr>
      <td width="1%"> &nbsp;</td>
      <td width="10%" valign="top"> Query </td>
      <td width="5%"  valign="top"> : </td>
      <td width="1%"> &nbsp;</td>
      <td width="60%">
        <g:textArea name="query" value="Hello benzene world, you are full of vitamin a" rows="10" cols="100"></g:textArea>
      </td>
      <td width="1%"> &nbsp;</td>
    </tr>

  <tr height='2'> <td> &nbsp; </td> </tr>

    <tr>
      <td width="1%"> &nbsp;</td>
      <td colspan="4" align="center">
        <g:actionSubmit value="Submit"  action="process"/>
      </td>
      <td width="1%"> &nbsp;</td>
    </tr>
   </table>
</g:form>
      </div>
<g:render template="/footer" />  
  </div>

</body>
</html>

tags/prototype-20100226/grails-app/views/discovery/process.gsp
<%--
  Created by IntelliJ IDEA.
  User: wohlgemuth
  Date: Feb 10, 2010
  Time: 8:49:40 PM
  To change this template use File | Settings | File Templates.
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head><title>Result</title></head>

<style type="text/css">@import url("${createLinkTo(dir: 'css',file : 'WebGUIStandards.css')}");</style>

<body topMargin=0 background="${createLinkTo(dir: 'images',file : 'FormBG.gif')}"  >
<div id="contents">

    <div id="main">
<table  border='0' width="100%" align='center' cellpadding="0" cellspacing="0">
	<tr>
		<td colspan="9" class="AppsLabel" align="center"> Result </td>
	</tr>

    <tr>
		<td colspan="9" align='right'>
                  [ <g:link controller="discovery" action="index">Back to discovery</g:link> ]
				  [ <g:link controller="homePage" action="index">Back to home</g:link> ]
	    </td>
	</tr>

  <tr height='2'> <td> &nbsp; </td> </tr>
</table>



<table border="0" id="tblSample" width="100%" align='center' cellpadding="3" cellspacing="0"class="TableBG" >

  <tr align='left' valign='bottom' class="TableHeaderBG">
        <td class="TableHeader" width="1%">&nbsp; </td>
        <td class="TableHeader" width="20%"> Name </td>
        <td class="TableHeader" width="1%">&nbsp; </td>
        <td class="TableHeader" width="20%"> Hash Key </td>
		<td class="TableHeader" width="1%">&nbsp;</td>
        <td class="TableHeader" width="15%">Discovered in Text</td>
        <td class="TableHeader" width="1%">&nbsp;</td>
        <td class="TableHeader" width="10%">Origin</td>
        <td class="TableHeader" width="1%">&nbsp;</td>
        <td class="TableHeader" width="20%"> Reference </td>
        <td class="TableHeader" width="1%">&nbsp; </td>
        <td class="TableHeader" width="5%"> Formula </td>
        <td class="TableHeader" width="1%">&nbsp;</td>
	</tr>


  <%
   
   if( result!=null && result.size() > 0 )
   {
    int liCnt=0;
    String lStrClass = "";
    String lColorFormulaBG = "";
    for(Map map : result)
    {
      Compound compound = map.compound

      if( compound==null)
         continue;

      if( liCnt++ % 2 == 0 )
      {
        lStrClass="TableRowBG2";
        lColorFormulaBG = "#FFFFFD";
      }
    else
      {
         lStrClass = "TableRowBG1";
         lColorFormulaBG = "#DBE8F6";
      }

      %>
  <tr class='<%=lStrClass%>'>
  <td class="Label3" width="1%">&nbsp;</td>
  <td class="Label3" valign="top" align="left">${compound.getDefaultName()}</td>
  <td class="Label3" width="1%">&nbsp;</td>
  <td class="Label3" valign="top" align="left"><g:link action="show" controller="compound" params="[id:compound.id]">${compound.inchiHashKey.completeKey}</g:link></td>
  <td class="Label3" width="1%">&nbsp;</td>
  <td class="Label3">${map.hit}</td>
  <td class="Label3" width="1%">&nbsp;</td>
  <td class="Label3">${map.resolver}</td>
  <td class="Label3" width="1%">&nbsp;</td>
  <td class="Label3">${map.result}</td>
  <td class="Label3" width="1%">&nbsp;</td>
  <td class="Label3" valign="top" align="center"><g:structureThumb inchi="${compound.inchi}" id="${compound.id}" color="${lColorFormulaBG}" /></td>
  <td class="Label3" width="1%">&nbsp;</td>

  </tr>
      <%
    }
        }else
    {
  %>
  <tr >
  <td class="Label3" width="1%">&nbsp;</td>
  <td class="Label3" colspan="11">
       <table border=0 align ="center" width="98%" class="TableBG">
         <tr> <td height='20' > </td> </tr>

			<tr bgcolor="Gray">
			   <td height='2' align='center' valign="middle" ></td>
			</tr>
			<tr>
			   <td align='center' height='70' valign="middle" > <font color='red' > No Compound Found... </font> </td>
			</tr>
			<tr bgcolor="Gray">
			   <td height='2' align='center' valign="middle" ></td>
			</tr>
			<tr> <td height='20' > </td> </tr>
        </table>
  </td>
  <td class="Label3" width="1%">&nbsp;</td>
  

  <% } %>


</table>
</div>
<g:render template="/footer" />
</div>
</body>
</html>