trunk/compound-repository/grails-app/controllers/compound/repository/HomePageController.groovy
package compound.repository

import compound.repository.entries.Compound

class HomePageController {

  def index = {

    // Remove session attribute
    if (session.getAttribute("ids") != null) {
      session.removeAttribute "ids"
    }
    if (session.getAttribute("query") != null) {
      session.removeAttribute "query"
    }

    def strQuery = "";
    if (params.query != null) {
      strQuery = params.query
    }

    return [query: strQuery]
  }

  def show_help_remote = {
    render """<div class="message">"Enter Query Like<br>chebi:*&nbsp;,glucose&nbsp;,benzene&nbsp;,C00001&nbsp;,XLYOFNOQVPJJNP-UHFFFAOYSA-N etc.</div>"""
  }

  def show_help_mol_remote = {
    render """<div class="message">"Please paste a standard mol file into this box and we will search the database against it</div>"""
  }
}

trunk/compound-repository/grails-app/controllers/compound/repository/MassLookupController.groovy
package compound.repository

import compound.repository.entries.Compound
import util.ConvertHelper

class MassLookupController {

    /**
     * does the actual converting of data
     */
    ConvertService convertService
    DataExportService dataExportService = new DataExportService();

    def index =
        {
            String ids = ""
            String from = params.from
            def to = params.to

            log.info "from: ${from}"
            log.info "to: ${from}"


            if (session.getAttribute("ids") != null) {
                ids = session.getAttribute("ids").toString()
            }

            if (params.from != null) {
                from = params.from

            }

            if (params.to != null) {
                to = params.to
            }

            return [fromFields: ConvertHelper.getInstance().getFromConversions(), toFields: ConvertHelper.getInstance().getToConversions(), ids: ids, from: from, to: to]
        }

    /**
     * process list of ids and returns a map containning all the found Compounds
     */
    def masstransform =
        {


            String id = "transform_content"
            session[id] = null

            String from = params.from
            def StrTo = params.to
            String ids = ""


            if (params.ids != null) {
                ids = params.ids
                session.setAttribute("ids", ids);
            }
            else {
                ids = session.getAttribute("ids").toString()
            }

            if (ids == null || ids.trim().length() == 0) {
                flash.message = "Error! Ids parameter is mandatory, Please Enter some ids."
                redirect(action: "index")
            } else {
                if (from == null || from.toString().equalsIgnoreCase("NULL")) {
                    flash.message = "Error! From parameter is mandatory."
                    redirect(action: "index")
                } else {
                    if (StrTo == null) {
                        flash.message = "Error! To parameter is mandatory, Please select at least one."
                        redirect(action: "index")
                    }
                }
            }

            def to = []

            if (StrTo instanceof String) {
                to.add StrTo.trim()
            } else {
                StrTo.each {String s ->
                    to.add s.trim()
                }

            }
            // prepare the list of ids : Start
            def list = []

            int counter = 0;

            ids.split("\n").each {String s ->
                if (counter < 100) {
                    flash.message = "sorry we only allow up to 100 convertions at a time, please use the webservice API in case you like to convert more ids at once. All id's after 100 have been removed. This limitation is due to performance and stability reasons and will be waved in a future version of this tool"
                    list.add s.trim()

                    counter++
                }
            }
            // prepare the list of ids : End


            if (params?.format && params.format != "html") //Export
            {

                //call the service to conver the data
                Collection<Map<Compound, ?>> transform = convertService.convert(from, to, list)

                params.put("to", to);
                dataExportService.exportMassLookUp(transform, response, params)

            } else {
                if (params.offset == null || params.offset.toString().equals("0")) {
                    params.put("offset", 0);
                } else {
                    params.put("offset", Long.parseLong("0" + params.offset.toString()));
                }

                if (params.max == null || params.max.toString().equals("0")) {
                    params.put("max", 10);
                } else {
                    params.put("max", Long.parseLong("0" + params.max.toString()));
                }

                //call the service to to get Count of the data
                Long total = 0;
                if (params.total == null || params.total.toString().equals("0")) {
                    total = convertService.getCount(from, to, list)
                } else {
                    total = Long.parseLong(params.total.toString())
                }

                //call the service to conver the data
                Collection<Map<Compound, ?>> result = convertService.convert(from, to, list, params)

                session[id] = result

                log.info "this request is accessible under: ${id}"

                return [transform: result, ids: ids, from: from, to: to, idsList: list, max: params.max, offset: params.offset, total: total, session_id: id]
            }
        }

    /**
     * returns the provide formats
     */
    static List getFormats() {
        return ['xml', 'json']
    }

    def show_help_remote = {
        render """<div class="message">Please enter some Ids in a vertical style like<br> <br>C00001 <br>C00002 <br>C00003 <br>C00004 <br>C00005 <br>C00006</div>"""
    }

}

trunk/compound-repository/grails-app/controllers/compound/repository/UtilAppsController.groovy
package compound.repository
class UtilAppsController {

    def index = { }
}

trunk/compound-repository/grails-app/views/utilApps/index.gsp
<%--
  Created by IntelliJ IDEA.
  User: pradeep
  Date: Mar 18, 2010
  Time: 11:53:12 PM
  To change this template use File | Settings | File Templates.
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
  <head><title><g:message code="MASS_LOOKUP" /></title>  <meta name="layout" content="main"/>
</head>


<body class="BodyBackground"  >
<g:form name="masslookup" controller="massLookup">

<div id="contents">

  <div id="main">

<table width="1000px"  border="0" align="center" height="100%">
  <tr>
    <td>
      <table  border='0' width="100%" align='center' cellpadding="0" cellspacing="0">
       <tr align='center' valign='bottom'>
          <td class="AppsLabel" align="center" style="COLOR: #0B3861; FONT-SIZE: 21px;FONT-FAMILY: 'Verdana';TEXT-TRANSFORM: capitalize">

              <g:message code="PROJECT_TITLE" />

          </td>
        </tr>

      <!--  <tr>
            <td  align='right' width="100%">
                      [ <g:link controller="homePage" action="index"><g:message code="HOME.BACK" /></g:link> ]
            </td>
        </tr>      -->
     </table>

    </td>
  </tr>

   <tr>
     <td>
      <div id="pagePath">
			<h1><g:link controller="homePage" action="index">Home</g:link> <span>&raquo;</span> <g:message code="UTIL_APPS" /></h1>
		</div>

<div class="line"></div>
      <table width="100%" >
         <tr>
              <td >
               <table border=0 align ="center" width="98%" class="TableBG">
               <tr> <td height='20'  > </td> </tr>

                  <tr bgcolor="Gray">
                     <td height='2' align='center' valign="middle" ></td>
                  </tr>
                  <tr>
                     <td align='center' height='70' valign="middle" > <font color='blue' > Under Construction </font> </td>
                  </tr>
                  <tr bgcolor="Gray">
                     <td height='2' align='center' valign="middle" ></td>
                  </tr>
                  <tr> <td height='20' > </td> </tr>
              </table>
              </td>
           </tr>
     </table>
</td>
   </tr>
</table>
</div>
  </div>

 </g:form>
  </body>

</html>